from __future__ import annotations
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field
from state import RetrievalState, CompanyQuery
from utils.llm import llm

_SYSTEM_PROMPT = """You are a financial search query rewriter for ASX mining company annual reports.

    Analyse the user's question and return three things:
    1. global_query — concise keywords optimised for document retrieval, spanning all mentioned companies
    2. companies — list of company ticker codes explicitly mentioned (BHP, RIO, FMG, MIN, NST).
    Return an empty list if no specific company is mentioned.
    3. company_queries — one company-specific retrieval query per company-specific request.

    Rules for global_query:
    - Keep company names and fiscal years explicit (e.g. "BHP FY2024").
    - Use standard financial terminology (e.g. "net profit", "revenue", "EBITDA", "capital expenditure").
    - Strip conversational filler ("please", "can you tell me", etc.).

    Rules for companies:
    - Only include companies explicitly named or clearly implied (e.g. "Fortescue" → "FMG").
    - Use uppercase ticker codes only: BHP, RIO, FMG, MIN, NST.
    - Return [] for general questions not tied to a specific company.

    Rules for company_queries:
    - Always create one item per company whenever multiple companies are mentioned, even if the same metric is requested for each.
    - Each item must contain company and query.
    - The query must include the company ticker, fiscal year if present, and the requested financial metric.
    - Return [] only for general questions not tied to any specific company.

    Examples:
    Input:  "What was BHP's FY2024 net profit?"
    Output: global_query="BHP FY2024 net profit"  companies=["BHP"]  company_queries=[{"company":"BHP","query":"BHP FY2024 net profit"}]

    Input:  "Compare revenue growth of Fortescue and Rio Tinto over three years"
    Output: global_query="Fortescue FMG Rio Tinto revenue growth FY2023 FY2024 FY2025"  companies=["FMG","RIO"]  company_queries=[{"company":"FMG","query":"FMG revenue growth FY2023 FY2024 FY2025"},{"company":"RIO","query":"RIO revenue growth FY2023 FY2024 FY2025"}]

    Input:  "What was BHP's FY2023 profit and RIO's FY2024 dividends?"
    Output: global_query="BHP FY2023 profit RIO FY2024 dividends"  companies=["BHP","RIO"]  company_queries=[{"company":"BHP","query":"BHP FY2023 profit"},{"company":"RIO","query":"RIO FY2024 dividends"}]

    Input:  "Rank BHP, RIO, FMG, MIN and NST by FY2024 EBITDA"
    Output: global_query="BHP RIO FMG MIN NST FY2024 EBITDA ranking"  companies=["BHP","RIO","FMG","MIN","NST"]  company_queries=[{"company":"BHP","query":"BHP FY2024 EBITDA"},{"company":"RIO","query":"RIO FY2024 EBITDA"},{"company":"FMG","query":"FMG FY2024 EBITDA"},{"company":"MIN","query":"MIN FY2024 EBITDA"},{"company":"NST","query":"NST FY2024 EBITDA"}]

    Input:  "How do mining companies usually report capital expenditure?"
    Output: global_query="mining company capital expenditure reporting"  companies=[]  company_queries=[]"""

 
class _QueryAnalysis(BaseModel):
    global_query: str = Field(description="Retrieval keywords spanning all mentioned companies.")
    companies: list[str] = Field(description="Uppercase tickers: BHP, RIO, FMG, MIN, NST. Empty if none.")
    company_queries: list[CompanyQuery] = Field(description="Company-specific retrieval queries. Empty if none.")


_structured_llm = llm.with_structured_output(_QueryAnalysis, method="function_calling")


def query_rewrite_node(state: RetrievalState) -> dict:
    query = state.get("query", "").strip()
    company_status = state.get("company_status") or {}
 
    # Retry path: company_status already initialised — only target missing companies.
    # Re-use the per-company queries generated by the first LLM call (already in
    # state.company_queries) so each retry query stays company-scoped and focused.
    if company_status:
        missing = [c for c, found in company_status.items() if not found]
        if not missing:
            return {}

        existing_cqs = {
            cq["company"]: cq["query"]
            for cq in (state.get("company_queries") or [])
        }
        unsupported_hints = state.get("unsupported_hints") or []
        company_queries = []

        for c in missing:
            base = existing_cqs.get(c)
            hints = [h for h in unsupported_hints if c in h]
            if hints and base:
                query_str = f"{base} {' '.join(hints)}"
            elif hints:
                query_str = " ".join(hints)
            else:
                query_str = base or f"{c} {state.get('rewritten_query') or query}"
            company_queries.append({"company": c, "query": query_str})

        return {"company_queries": company_queries}

    # First-run path: use LLM to rewrite query and initialise company_status.
    if not query:
        return {"rewritten_query": "", "companies": [], "company_queries": [], "company_status": {}}

    try:
        result: _QueryAnalysis = _structured_llm.invoke([
            SystemMessage(content=_SYSTEM_PROMPT),
            HumanMessage(content=query),
        ])
        
        return {
            "rewritten_query": result.global_query,
            "companies": result.companies,
            "company_queries": list(result.company_queries),
            "company_status": {c: False for c in result.companies},
        }
    except Exception:
        return {"rewritten_query": query, "companies": [], "company_queries": [], "company_status": {}}
